### PR TITLE
uBlock Origin should be allowed, just restricted.

### PR DESCRIPTION
**Pull request by s0urce-c0de**

### CODE REVIEW

**Comment by isaacfonner** [comment]
YES YES YES YES YES YES PLEASE

**Comment by catfoolyou** [comment]
even if not ublock, allow another good ablocker like adguard or adblock plus

**Comment by CaenJones** [comment]
Yes, I agree. Thank you for adding a PR! :D

**Comment by s0urce-c0de** [comment]
your welcome

**Pull request merged**
